version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    networks:
      - galaxie
    volumes:
      - elasticsearch:/usr/share/elasticsearch/
  kibana: 
    image: kibana:7.6.2
    ports:
      - 5601:5601
    networks:
      - galaxie
    volumes:
      - kibana:/usr/share/kibana/
   
  
volumes:
  elasticsearch:
  kibana: 
networks:
  galaxie:
